openapi: 3.0.0
info:
  title: LSTM Sentiment Analysis API
  description: API untuk prediksi sentimen menggunakan model LSTM
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
paths:
  /api/status:
    get:
      summary: Cek status API
      description: Endpoint untuk memeriksa apakah API berjalan.
      responses:
        '200':
          description: Status API
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "API is running"
  /api/predict/lstm:
    get:
      summary: Informasi tentang endpoint prediksi
      description: Endpoint untuk memberikan informasi cara menggunakan endpoint prediksi.
      responses:
        '200':
          description: Informasi tentang endpoint prediksi
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  example:
                    type: object
                    properties:
                      text:
                        type: string
                        example: "Your text here"
    post:
      summary: Prediksi Sentimen
      description: Ambil teks input dan prediksi sentimen menggunakan model LSTM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Saya sangat senang hari ini."
      responses:
        '200':
          description: Hasil prediksi sentimen
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  prediction:
                    type: string
                  confidence:
                    type: number
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/predict-file-lstm:
    post:
      tags:
        - Sentiment Analysis
      summary: Predict sentiment for text inputs from a file.
      description: Analyze the sentiment of multiple texts provided in a `.txt` file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Text file with one text per line to analyze.
      responses:
        '200':
          description: Sentiment predictions for each line in the file.
          content:
            application/json:
              schema:
                type: object
                properties:
                  predictions:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                          description: Original text.
                        processed_text:
                          type: string
                          description: Cleaned version of the text.
                        prediction:
                          type: string
                          description: Predicted sentiment (positive, neutral, negative).
                        confidence:
                          type: number
                          format: float
                          description: Confidence score of the prediction.
        '400':
          description: Invalid input or missing file parameter.
        '500':
          description: Internal server error.